### ISSUE TITLE
bower install does a core dump

### ISSUE THREAD

**Issue by PeteEverything** [diegotoral/generator-django-demo#2]
Hi there, I got almost to the point of running this server up, and got a segmentation fault (which  was fatal) as follows:

(generator-django-demo) pete-PC:/appl/projects/generator-django-demo/generator-django-demo$ bower install
Segmentation fault (core dumped)
(generator-django-demo) pete-PC:/appl/projects/generator-django-demo/generator-django-demo$ python ./manage.py runserver
Traceback (most recent call last):
  File "./manage.py", line 6, in <module>
    execute_from_command_line(sys.argv)
  File "/appl/projects/generator-django-demo/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/appl/projects/generator-django-demo/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/appl/projects/generator-django-demo/local/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/appl/projects/generator-django-demo/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/appl/projects/generator-django-demo/local/lib/python2.7/site-packages/django/conf/__init__.py", line 94, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/appl/projects/generator-django-demo/local/lib/python2.7/site-packages/generator-django-demo/settings/development.py", line 4
    from generator-django-demo.settings.common import *
                  ^
SyntaxError: invalid syntax 

Any ideas what might be the problem with bower?

**Comment by diegotoral** [comment]
Hello @PeteEverything!

I haven't used `bower` for while now but have you tried `npm cache clean` and installed `bower` again?

**Comment by PeteEverything** [comment]
Thanks, I will give it a try.
